title: Product
pages: true
files: true
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  sold:
    label: Sold?
    type: toggle
    default: no
  prodIndex:
    label: Index
    type: Text
  
